#!/usr/bin/env python
import syslog
import pydaemonize

def daemon():
    syslog.openlog(ident='seqlabd', facility=syslog.LOG_DAEMON)
    

    syslog.syslog(syslog.LOG_INFO, 'Started.')

if __name__ == '__main__':
   pydaemonize.serviced(daemon)
