#!/usr/bin/env python
import syslog
import pydaemonize
import seqlablib

def daemon():
    syslog.openlog(ident='seqlabd', facility=syslog.LOG_DAEMON)
    conf = seqlablib.Ref()
    conf.put(seqlablib.read_configuration)

    syslog.syslog(syslog.LOG_INFO, 'Started.')

if __name__ == '__main__':
   pydaemonize.serviced(daemon)
